<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <InternalsVisibleTo Include="SharpCampus.BotServer.Tests" />
    <InternalsVisibleTo Include="SharpCampus.LoadTest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="MagicOnion.Client" />
    <PackageReference Include="R3" />
    <PackageReference Include="ZLinq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpCampus.Shared\SharpCampus.Shared.csproj" />
    <ProjectReference Include="..\SharpCampus.Shared.Internal\SharpCampus.Shared.Internal.csproj" />
    <ProjectReference Include="..\SharpCampus.Server.Common\SharpCampus.Server.Common.csproj" />
    <ProjectReference Include="..\SharpCampus.GameCore\SharpCampus.GameCore.csproj" />
  </ItemGroup>

</Project>
