<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SharpCampus.Shared\SharpCampus.Shared.csproj" />
    <ProjectReference Include="..\SharpCampus.Shared.Internal\SharpCampus.Shared.Internal.csproj" />
    <ProjectReference Include="..\SharpCampus.Server.Common\SharpCampus.Server.Common.csproj" />
  </ItemGroup>

</Project>
