<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="MagicOnion.Client" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="ZString" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpCampus.Shared\SharpCampus.Shared.csproj" />
    <ProjectReference Include="..\SharpCampus.Client.Common\SharpCampus.Client.Common.csproj" />
  </ItemGroup>

</Project>
