<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MagicOnion.Server" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="ZLogger" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpCampus.Shared\SharpCampus.Shared.csproj" />
  </ItemGroup>

</Project>
