<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SharpCampus.MasterDataTool.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ConsoleAppFramework">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpCampus.Shared\SharpCampus.Shared.csproj" />
  </ItemGroup>

</Project>
